/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ecrimebureau.Web;

import com.ecrimebureau.File.Hash;
import com.ecrimebureau.File.HashValue;
import com.ecrimebureau.Web.Entity.WhoisS;
import java.security.MessageDigest;

/**
 *
 * @author e-Crime
 */
public class JIFHash extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public JIFHash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTFStringToHash = new javax.swing.JTextField();
        jBtnQickHash = new javax.swing.JButton();
        jBtnHash = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCBAlgorithim = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Hash");
        setToolTipText("");

        jSplitPane1.setDividerLocation(450);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTFStringToHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFStringToHashActionPerformed(evt);
            }
        });
        jTFStringToHash.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jTFStringToHashCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTFStringToHashInputMethodTextChanged(evt);
            }
        });
        jTFStringToHash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFStringToHashKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFStringToHashKeyPressed(evt);
            }
        });

        jBtnQickHash.setText("Quick Hash");
        jBtnQickHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnQickHashActionPerformed(evt);
            }
        });

        jBtnHash.setText("Hash");
        jBtnHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHashActionPerformed(evt);
            }
        });

        jProgressBar1.setToolTipText("");
        jProgressBar1.setName(""); // NOI18N
        jProgressBar1.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFStringToHash)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnQickHash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnHash)
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFStringToHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnQickHash)
                        .addComponent(jBtnHash))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel1.setBorder(null);

        jLabel1.setText("Algorithim");

        jCBAlgorithim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MD5", "SHA1", "SHA-256", "SHA-384", "SHA-512" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addComponent(jCBAlgorithim, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBAlgorithim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnQickHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnQickHashActionPerformed
      try{
      jTextArea1.setText(HashValue.getChecksum(this.jTFStringToHash.getText().trim(),jCBAlgorithim.getSelectedItem().toString()));
     
     
      }catch(Exception ex){
          ex.printStackTrace();
          
      }
    }//GEN-LAST:event_jBtnQickHashActionPerformed

    private void jBtnHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHashActionPerformed
       Hash hash = new Hash(this,jTextArea1,jCBAlgorithim.getSelectedItem().toString().trim(),jProgressBar1);
       hash.execute();
      
       
    }//GEN-LAST:event_jBtnHashActionPerformed

    private void jTFStringToHashInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTFStringToHashInputMethodTextChanged
       
        
    }//GEN-LAST:event_jTFStringToHashInputMethodTextChanged

    private void jTFStringToHashCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTFStringToHashCaretPositionChanged
       
    }//GEN-LAST:event_jTFStringToHashCaretPositionChanged

    private void jTFStringToHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFStringToHashActionPerformed
      
    }//GEN-LAST:event_jTFStringToHashActionPerformed

    private void jTFStringToHashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFStringToHashKeyTyped
       
    }//GEN-LAST:event_jTFStringToHashKeyTyped

    private void jTFStringToHashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFStringToHashKeyPressed
        
    }//GEN-LAST:event_jTFStringToHashKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnHash;
    private javax.swing.JButton jBtnQickHash;
    private javax.swing.JComboBox jCBAlgorithim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTFStringToHash;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
